### ISSUE TITLE
How to use the same db in multiple processes?

### ISSUE THREAD

**Issue by Hitaylor** [gavioto/fastdb#2]
I am using the fastdb as cache in ROS applications. Open the db and use it in multiple threads is available. But how to use a db in multiprocess? For example, we receive data  in a ros_node and use the data in another ros_node.

**Comment by slidertom** [comment]
Probbaly you have to use:
http://www.garret.ru/fastdb/FastDB.htm#cli

E.g.: I'm using in such way: threads+fastdb for the real time operations and apache+json+fastdb for the interaction with other (local, non-local) processes,

**Comment by Hitaylor** [comment]
> Probbaly you have to use:
> http://www.garret.ru/fastdb/FastDB.htm#cli
> 
> E.g.: I'm using in such way: threads+fastdb for the real time operations and apache+json+fastdb for the interaction with other (local, non-local) processes,

Thanks.
Now I'm using the "dbConcurrentUpdate" mode to access the database, and multi-process can open the same db file, then write/read on the same db file.
